### ISSUE TITLE
update theme to the newest svbtle version

### ISSUE THREAD

**Issue by orlando** [orlando/svbtle-jekyll#2]
this repo has the old svbtle theme. The current svbtle theme looks like this one.

![wf_dt0bsshevksavhqztdldzq8f9vqegzzuf5jzrucw](https://f.cloud.github.com/assets/849872/1770050/08a4432a-6780-11e3-9896-2fc33843c407.png)

**Comment by sappleg** [comment]
@orlando, is this still in development?

**Comment by orlando** [comment]
@spencerapplegate yeah, maybe I'll put some time in the week to work on this.. later this week should be ready.

Thanks

**Comment by orlando** [comment]
solved by #4
